openapi: 3.0.0
info:
  title: ''
  version: 2.2.1
  description: ''
servers:
  - url: http://localhost:8081
paths:
  /v1/users:
    get:
      summary: Возвращает список
      parameters:
        - name: limit
          in: query
          description: Лимит списка
          schema:
            type: number
      responses:
        '200':
          description: OK
    post:
      summary: Создать юзера
      responses:
        '200':
          description: OK
  /v1/users/:id:
    get:
      summary: Возвращает не список
      responses:
        '200':
          description: OK
  /auth/login:
    post:
      summary: Возвращает не список
      responses:
        '200':
          description: OK